version: "3.8"

services:
  api:
    env_file:
      - .env
    build: .
    ports:
      - 5000:5000
    container_name: api
    restart: on-failure
    depends_on:
      - mysql
  mysql:
    env_file:
      - .env
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - ./traffic.sql:/docker-entrypoint-initdb.d/traffic.sql
      - my-db:/var/lib/mysql
volumes:
  my-db:
